version: "3.8"
services:
  notebooks:
    build: ./app
    ports:
      - "8001:8888"
    volumes:
      - type: bind
        source: ./app
        target: /home/jovyan/work
      - type: bind
        source: ./data
        target: /home/jovyan/data